### ISSUE TITLE
Adding support for iOS

### ISSUE THREAD

**Issue by EricsG95** [triniwiz/nativescript-accordion#1]
What is the restriction that make this plugin only supported by Android? Thank you

**Comment by triniwiz** [comment]
It uses a android only lib but i'm currently working on adding iOS atm 😄

**Comment by EricsG95** [comment]
I see, appreciate! It is a great project, looking forward for your release in the future for iOS!

**Comment by triniwiz** [comment]
So this is currently done just need to update a pod and publish the new code

**Comment by triniwiz** [comment]
@EricsG95 you can update to `2.0.0` for iOS support 😄

**Comment by EricsG95** [comment]
Thank you so much! Gonna to try immediately!
