### ISSUE TITLE
Custom accordion header

### ISSUE THREAD

**Issue by HoangJK** [triniwiz/nativescript-accordion#10]
Hello,

Nice to use your plugin! 
And I wonder It's so good if you can add a right icon for Accordion header.
Like this image:
![accordion](https://cloud.githubusercontent.com/assets/12653469/23251327/78b7d736-f9df-11e6-96fb-37d3d00eada7.png)

This is my suggest for your plugin,

Thanks.

**Comment by triniwiz** [comment]
This can be done in 3.0 with a custom header
