### ISSUE TITLE
Invoke virtual method error

### ISSUE THREAD

**Issue by lukeramsden** [triniwiz/nativescript-accordion#11]
Hey, when I try to put in a Repeater inside the accordion, I get this error:

`java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getImportantForAccessibility()' on a null object reference`

I get this on Android, haven't tested on iOS.

Heres the full error log: http://pastebin.com/80kjR0LM

The reason I am using a repeater is because the accordion is based upon a JavaScript array, but I'm not sure of the proper way to create accordion items from code.

**Comment by triniwiz** [comment]
Fixed in 3.0
