### ISSUE TITLE
Undefined Exception while adding to angular nativescript

### ISSUE THREAD

**Issue by chandansutradhar2** [triniwiz/nativescript-accordion#23]
I tried following the example for angular native but am recieving the following exception

System.err: com.tns.NativeScriptException:
System.err: Calling js method getGroupView failed
System.err: TypeError: Cannot read property 'setBackgroundColor' of undefined
System.err: File: "file:///data/data/com.FreeQuote/files/app/tns_modules/nativescript-accordion/src/android/accordion.js, line: 251, column: 29
System.err: StackTrace:
System.err:     Frame: function:'AccordionListAdapter.getGroupView', file:'file:///data/data/com.FreeQuote/files/app/tns_modules/nativescript-accordion/src/android/
accordion.js', line: 251, column: 30
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:953)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:937)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:929)
System.err:     at com.tns.gen.android.widget.BaseExpandableListAdapter_frnal_ts_helpers_l58_c38__AccordionListAdapter.getGroupView(BaseExpandableListAdapter_frnal_
ts_helpers_l58_c38__AccordionListAdapter.java:33)
System.err:     at android.widget.ExpandableListConnector.getView(ExpandableListConnector.java:446)
System.err:     at android.widget.AbsListView.obtainView(AbsListView.java:2346)
System.err:     at android.widget.ListView.measureHeightOfChildren(ListView.java:1280)
System.err:     at android.widget.ListView.onMeasure(ListView.java:1188)
System.err:     at android.view.View.measure(View.java:18788)
System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     at org.nativescript.widgets.StackLayout.onMeasure(StackLayout.java:83)
System.err:     at android.view.View.measure(View.java:18788)
System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     at org.nativescript.widgets.StackLayout.onMeasure(StackLayout.java:83)
System.err:     at android.view.View.measure(View.java:18788)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
System.err:     at android.view.View.measure(View.java:18788)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
System.err:     at android.view.View.measure(View.java:18788)
System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     at org.nativescript.widgets.MeasureHelper.measureChildFixedColumnsAndRows(GridLayout.java:1055)
System.err:     at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:865)
System.err:     at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:279)
System.err:     at android.view.View.measure(View.java:18788)
System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     at org.nativescript.widgets.ContentLayout.onMeasure(ContentLayout.java:32)
System.err:     at android.view.View.measure(View.java:18788)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
System.err:     at android.view.View.measure(View.java:18788)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
System.err:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
System.err:     at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
System.err:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
System.err:     at android.view.View.measure(View.java:18788)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
System.err:     at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
System.err:     at android.view.View.measure(View.java:18788)
System.err:     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
System.err:     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:670)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:606)
System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
System.err:     at android.os.Handler.handleCallback(Handler.java:739)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:148)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
ActivityManager: Process com.FreeQuote (pid 5728) has died

package.json details are
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.FreeQuote",
    "tns-android": {
      "version": "3.2.0"
    }
  },
  "scripts": {
    "lint": "tslint \"app/**/*.ts\""
  },
  "dependencies": {
    "@angular/animations": "4.2.5",
    "@angular/common": "4.2.5",
    "@angular/compiler": "4.2.5",
    "@angular/core": "4.2.5",
    "@angular/forms": "4.2.5",
    "@angular/http": "4.2.5",
    "@angular/platform-browser": "4.2.5",
    "@angular/router": "4.2.5",
    "angular2-signaturepad": "^2.6.1",
    "nativescript-accordion": "^5.0.2",
    "nativescript-angular": "4.2.0",
    "nativescript-autocomplete": "^1.0.0",
    "nativescript-contacts": "^1.5.3",
    "nativescript-couchbase": "^1.0.18",
    "nativescript-drop-down": "^3.1.1",
    "nativescript-feedback": "^1.0.6",
    "nativescript-floatingactionbutton": "^3.0.1",
    "nativescript-telerik-ui": "3.0.4",
    "nativescript-theme-core": "1.0.4",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.4.3",
    "tns-core-modules": "^3.2.0",
    "zone.js": "0.8.16"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "codelyzer": "3.1.2",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "1.3.0",
    "nativescript-dev-typescript": "0.5.0",
    "node-sass": "4.5.3",
    "tslint": "5.6.0",
    "typescript": "2.4.2",
    "tns-core-modules": "^3.2.0 || ^3.3.0-2017-09-08-9851"
  }
}

My Summary.component.html file details are
  <Accordion [items]="items" itemTapped="tapped" headerTextBold="true" headerTextColor="white" headerColor="pink" headerTextColor="blue"
        allowMultiple="true" id="ac" selectedIndex="2">

        <ng-template accordionHeaderTemplate let-item="item" let-i="index">
            <GridLayout backgroundColor="blue" columns="auto,*">
                <Label [text]="item.title"></Label>
            </GridLayout>
        </ng-template>

        <ng-template accordionItemTemplate let-item="item" let-parent="parentIndex" let-even="even" let-child="childIndex">
            <StackLayout>
                <Image [src]="item.image"></Image>
                <Label [text]="item.text"></Label>
            </StackLayout>
        </ng-template>

        
        <ng-template accordionFooterTemplate let-item="item" let-i="index">
            <GridLayout backgroundColor="yellow" columns="auto,*">
                <Label [text]="item.footer"></Label>
                <Label col="1" text="-"></Label>
            </GridLayout>
        </ng-template>
    </Accordion>

Have also added, items array inside component  constructor, still getting this error.

Any help would be appreciated.

**Comment by triniwiz** [comment]
What does the items array look like ?

**Comment by TheOnlyMatt** [comment]
Hello !
I'm facing the same problem

I have the following HTML 
`<Accordion [items]="contacts" itemTapped="tapped" headerTextBold="true" headerTextColor="white" headerColor="pink" headerTextColor="blue"
               allowMultiple="true"  selectedIndex="2">

        <ng-template accordionHeaderTemplate let-item="contact" let-i="index">
            <GridLayout backgroundColor="blue" columns="auto">
                <Label [text]="contact.title.rendered"></Label>
            </GridLayout>
        </ng-template>

        <ng-template accordionItemTemplate let-item="contact" let-parent="parentIndex" let-even="even" let-child="childIndex">
            <StackLayout>
                <Label textWrap="true" [text]="contact.acf.fonction" class="position" ></Label>
            </StackLayout>
        </ng-template>

    </Accordion>`

No specific TS related to the view, and when the view is opened, this undefined background color error is thrown.

Any idea ?

**Comment by pdomkar** [comment]
I get this error too.
Any solution? @triniwiz 

System.err: com.tns.NativeScriptException:
System.err: Calling js method getGroupView failed
System.err:
System.err: TypeError: Cannot read property 'setBackgroundColor' of undefined
System.err: File: "file:///data/data/org.nativescript.SkautISmobile/files/app/tns_modules/nativescript-accordion/src/android/accordion.js, line: 251, column: 29
System.err:
System.err: StackTrace:
