### ISSUE TITLE
Nested Accordion

### ISSUE THREAD

**Issue by Khadreal** [triniwiz/nativescript-accordion#26]
I'm trying to have a nested accordion, is this possible ?

Thanks

**Comment by Khadreal** [comment]
Has anyone find a solution to this

**Comment by shivgolani** [comment]
Hi any luck with this?

**Comment by triniwiz** [comment]
It should be possible now by nesting the accordion in [this](https://github.com/triniwiz/nativescript-nested-scrollview)
