### ISSUE TITLE
Typeerror: rootLocator is not a function

### ISSUE THREAD

**Issue by DeepikaKochar** [triniwiz/nativescript-accordion#30]
I am getting this error :

System.err: com.tns.NativeScriptException:
System.err: Calling js method getGroupView failed
System.err:
System.err: TypeError: rootLocator is not a function
System.err: File: "file:///data/data/com.demotuc/files/app/tns_modules/nativescript-accordion/angular/index.js, line: 17, column: 11
System.err:
System.err: StackTrace:
System.err:     Frame: function:'getItemViewRoot', file:'file:///data/data/com.demotuc/files/app/tns_modules/nativescript-accordion/angular/index.js', line: 17, column: 12
System.err:     Frame: function:'AccordionComponent.headerLoading', file:'file:///data/data/com.demotuc/files/app/tns_modules/nativescript-accordion/angular/index.js', line: 131, column: 25
System.err:     Frame: function:'Observable.notify', file:'file:///data/data/com.demotuc/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 100, column: 32
System.err:     Frame: function:'notifyForHeaderOrFooterAtIndex', file:'file:///data/data/com.demotuc/files/app/tns_modules/nativescript-accordion/src/android/accordion.js', line: 25, column: 11
System.err:     Frame: function:'AccordionListAdapter.getGroupView', file:'file:///data/data/com.demotuc/files/app/tns_modules/nativescript-accordion/src/android/accordion.js', line: 225, column: 21
System.err:
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     at com.tns.gen.android.widget.BaseExpandableListAdapter_frnal_ts_helpers_l58_c38__AccordionListAdapter.getGroupView(BaseExpandableListAdapter_frnal_ts_helpers_l58_c38__AccordionListAdapter.java:33)
System.err:     at android.widget.ExpandableListConnector.getView(ExpandableListConnector.java:446)
System.err:     at android.widget.AbsListView.obtainView(AbsListView.java:2362)
System.err:     at android.widget.ListView.onMeasure(ListView.java:1203)
System.err:     at android.view.View.measure(View.java:19734)
System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     at org.nativescript.widgets.VerticalScrollView.onMeasure(VerticalScrollView.java:118)
System.err:     at android.view.View.measure(View.java:19734)
System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     at org.nativescript.widgets.StackLayout.onMeasure(StackLayout.java:83)
System.err:     at android.view.View.measure(View.java:19734)
System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     at org.nativescript.widgets.StackLayout.onMeasure(StackLayout.java:83)
System.err:     at android.view.View.measure(View.java:19734)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
System.err:     at android.view.View.measure(View.java:19734)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
System.err:     at android.view.View.measure(View.java:19734)
System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     at org.nativescript.widgets.MeasureHelper.measureChildFixedColumnsAndRows(GridLayout.java:1055)
System.err:     at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:865)
System.err:     at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:279)
System.err:     at android.view.View.measure(View.java:19734)
System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     at org.nativescript.widgets.ContentLayout.onMeasure(ContentLayout.java:32)
System.err:     at android.view.View.measure(View.java:19734)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
System.err:     at android.view.View.measure(View.java:19734)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
System.err:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
System.err:     at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
System.err:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
System.err:     at android.view.View.measure(View.java:19734)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
System.err:     at com.android.internal.policy.DecorView.onMeasure(DecorView.java:687)
System.err:     at android.view.View.measure(View.java:19734)
System.err:     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2271)
System.err:     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1358)
System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1607)
System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:683)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:619)
System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
System.err:     at android.os.Handler.handleCallback(Handler.java:751)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:154)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6077)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

Package.json: 
"dependencies": {
    "@angular/animations": "~4.0.0",
    "@angular/common": "~4.0.0",
    "@angular/compiler": "~4.0.0",
    "@angular/core": "~4.0.0",
    "@angular/forms": "~4.0.0",
    "@angular/http": "~4.0.0",
    "@angular/platform-browser": "~4.0.0",
    "@angular/platform-browser-dynamic": "~4.0.0",
    "@angular/router": "~4.0.0",
    "base-64": "^0.1.0",
    "nativescript-accordion": "^5.0.3",
    "nativescript-angular": "~3.0.0",
    "nativescript-downloader": "^1.0.3",
    "nativescript-drop-down": "^3.1.3",
    "nativescript-pdf-view": "^2.0.1",
    "nativescript-plugin-firebase": "^4.1.1",
    "nativescript-pro-ui": "^3.2.0",
    "nativescript-snackbar": "^1.1.7",
    "nativescript-social-login": "^1.8.2",
    "nativescript-social-share": "^1.4.0",
    "nativescript-sqlite": "^1.1.7",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-toast": "^1.4.6",
    "nativescript-webview-interface": "^1.4.1",
    "nativescript-xml2js": "^0.5.2",
    "nativescript-zip": "^1.3.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.2.0",
    "tns-core-modules": "^3.3.0",
    "zone.js": "0.8.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.0.0",
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "^0.4.0",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "typescript": "^2.4.0",
    "resolve-url-loader": "~2.1.0"
  },

Android version: 3.3.1

**Comment by DeepikaKochar** [comment]
Resolved by upgrading dependencies. :)

**Comment by triniwiz** [comment]
I’ll update the readme because there are specific versions to use with nativescript-angular
