### ISSUE TITLE
TypeError: this._trackByFn is not a function

### ISSUE THREAD

**Issue by westlakem** [triniwiz/nativescript-accordion#31]
Just added this to my existing project, and got the following error:

```
JS: ERROR TypeError: this._trackByFn is not a function
JS: ERROR CONTEXT [object Object]
```

Unfortunately I don't have anymore information in the log than that

Nativescript+Angular

**Comment by vasyliv** [comment]
same bug

**Comment by chauhan-saurabh** [comment]
same issue

**Comment by westlakem** [comment]
@vasyliv @chauhan-saurabh  Please see the PR that is linked.  It hasn't been accepted yet but that's what fixes it if you want to do that manually.

**Comment by leosilvestre7** [comment]
i have the same bug

**Comment by leosilvestre7** [comment]
update angular/index.js

**Comment by RadouaneRoufid** [comment]
same here

**Comment by triniwiz** [comment]
I know this bug has been annoying but i plan to upgrade this plugin like i did with the pager so it will support multi templates and it should also improve the performance

**Comment by Dalf91x** [comment]
same here
