### ISSUE TITLE
Sample won't compile

### ISSUE THREAD

**Issue by gordingin** [triniwiz/nativescript-accordion#34]
I just cloned the repo and did a npm i, then tns platform add android, then a tns run android and received these errors.

C:\git\nativescript-accordion\demo-ng>tns run android
Searching for devices...
Executing before-liveSync hook from C:\git\nativescript-accordion\demo-ng\hooks\before-liveSync\nativescript-angular-sync.js
Executing before-prepare hook from C:\git\nativescript-accordion\demo-ng\hooks\before-prepare\nativescript-dev-android-snapshot.js
Executing before-prepare hook from C:\git\nativescript-accordion\demo-ng\hooks\before-prepare\nativescript-dev-typescript.js
Found peer TypeScript 2.3.4
../angular/index.ts(16,8): error TS2307: Cannot find module '@angular/core'.

../angular/index.ts(17,57): error TS2307: Cannot find module 'nativescript-angular/element-registry'.

../angular/index.ts(18,22): error TS2307: Cannot find module 'ui/core/view'.
../angular/index.ts(19,33): error TS2307: Cannot find module 'data/observable-array'.
../angular/index.ts(20,28): error TS2307: Cannot find module 'data/observable'.
../angular/index.ts(21,25): error TS2307: Cannot find module 'nativescript-angular/lang-facade'.

node_modules/@angular/common/src/directives/ng_class.d.ts(48,34): error TS2304: Cannot find name 'Set'.
node_modules/@angular/compiler/src/aot/compiler.d.ts(48,32): error TS2304: Cannot find name 'Map'.

node_modules/@angular/compiler/src/compile_metadata.d.ts(369,20): error TS2304: Cannot find name 'Set'.

node_modules/@angular/compiler/src/compile_metadata.d.ts(371,28): error TS2304: Cannot find name 'Set'.
node_modules/@angular/compiler/src/compile_metadata.d.ts(373,15): error TS2304: Cannot find name 'Set'.
node_modules/@angular/compiler/src/compile_metadata.d.ts(375,23): error TS2304: Cannot find name 'Set'.
node_modules/@angular/compiler/src/compile_metadata.d.ts(377,17): error TS2304: Cannot find name 'Set'.
node_modules/@angular/compiler/src/compile_metadata.d.ts(379,25): error TS2304: Cannot find name 'Set'.

node_modules/@angular/compiler/src/output/output_ast.d.ts(444,63): error TS2304: Cannot find name 'Set'.

node_modules/@angular/core/src/change_detection/differs/default_iterable_differ.d.ts(28,32): error TS2304: Cannot find name 'Iterable'.
node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(24,16): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(32,16): error TS2304: Cannot find name 'Map'.

node_modules/@angular/core/src/change_detection/differs/iterable_differs.d.ts(15,48): error TS2304: Cannot find name 'Iterable'.

node_modules/@angular/core/src/change_detection/differs/keyvalue_differs.d.ts(23,18): error TS2304: Cannot find name 'Map'.

node_modules/@angular/core/src/di/reflective_provider.d.ts(87,123): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/di/reflective_provider.d.ts(87,165): error TS2304: Cannot find name 'Map'.

node_modules/@angular/platform-browser/src/browser/browser_adapter.d.ts(79,33): error TS2304: Cannot find name 'Map'.

node_modules/@angular/platform-browser/src/dom/dom_adapter.d.ts(97,42): error TS2304: Cannot find name 'Map'.

node_modules/@angular/platform-browser/src/dom/shared_styles_host.d.ts(11,30): error TS2304: Cannot find name 'Set'.
node_modules/@angular/platform-browser/src/dom/shared_styles_host.d.ts(22,30): error TS2304: Cannot find name 'Set'.

node_modules/nativescript-angular/dom-adapter.d.ts(79,34): error TS2304: Cannot find name 'Map'.

node_modules/rxjs/Observable.d.ts(68,60): error TS2693: 'Promise' only refers to a type, but is being used as a value here.

node_modules/tns-core-modules/ui/core/view-base/view-base.d.ts(188,24): error TS2304: Cannot find name 'Set'.

node_modules/tns-core-modules/ui/core/view-base/view-base.d.ts(189,30): error TS2304: Cannot find name 'Set'.

node_modules/tns-core-modules/ui/core/view/view.d.ts(309,17): error TS2304: Cannot find name 'Set'.

node_modules/tns-core-modules/ui/core/view/view.d.ts(310,23): error TS2304: Cannot find name 'Set'.
node_modules/tns-core-modules/ui/styling/css-selector/css-selector.d.ts(16,18): error TS2304: Cannot find name 'Set'.

node_modules/tns-core-modules/ui/styling/css-selector/css-selector.d.ts(17,24): error TS2304: Cannot find name 'Set'.
node_modules/tns-core-modules/ui/styling/css-selector/css-selector.d.ts(57,41): error TS2304: Cannot find name 'Map'.
node_modules/tns-core-modules/ui/styling/css-selector/css-selector.d.ts(60,18): error TS2304: Cannot find name 'Set'.
node_modules/tns-core-modules/ui/styling/css-selector/css-selector.d.ts(61,21): error TS2304: Cannot find name 'Set'.
references.d.ts(1,1): error TS6053: File 'C:/git/nativescript-accordion/node_modules/tns-platform-declarations/ios.d.ts' not found.

Preparing project...

It never finishes..

Thanks
Ralph

**Comment by gordingin** [comment]
actually it did finish with this.

Unable to apply changes on device: 192.168.203.101:5555. Error is: Processing node_modules failed. Error: cp: cannot create directory 'C:/git/nativescript-accor
dion/demo-ng/platforms/android/src/main/assets/app/tns_modules': No such file or directory.

**Comment by dondre** [comment]
Ran across a similar issue. I fixed this but boosting my compileOptions in tsconfig from ES5 to ESNEXT. 

`{
  "compilerOptions": {
    "target": "ESNEXT",
   ......
}`
