### ISSUE TITLE
Problem rendering within a ScrollView layout

### ISSUE THREAD

**Issue by RadouaneRoufid** [triniwiz/nativescript-accordion#35]
I'm using Accordion in my nativescript-angular app. Accordion works great within a Stack ou Grid Layout. But It does not render correctly within a ScrollView. 

To reproduce :

```
<ScrollView>
    <GridLayout>
    <Accordion [items]="items">

        <ng-template accordionHeaderTemplate let-item="item" let-i="index">
            <GridLayout backgroundColor="blue" columns="auto,*">
                <Label [text]="item.name"></Label>
            </GridLayout>
        </ng-template>

        <ng-template accordionItemTemplate let-item="item">
            <StackLayout>
                <Label [text]="item.name"></Label>
            </StackLayout>
        </ng-template>

    </Accordion>
    </GridLayout>
</ScrollView>
```

**Comment by triniwiz** [comment]
I haven’t tried this but accordion is basically a fancy listview which has a scroll already so you would be stacking scrollviews

**Comment by RadouaneRoufid** [comment]
The problem is that all the content after my accordion is hidden when I collapse the accordion. The only solution I found for now is ScrollView !!

**Comment by triniwiz** [comment]
Ok I’ll look into this does it happen on both platforms?

**Comment by RadouaneRoufid** [comment]
I only tested on an android platform.

**Comment by venkateshsj** [comment]
I too checked the same. If the accordion is anywhere inside a ScrollView, it does not function as expected. I created a separate page with accordion without ScrollView on the page and it worked as expected.

Observed this issue on Android. I have not checked it on iOS. I will report as soon as I can check it on iOS.

Any suggestions/solutions are welcome to resolve this issue, without it this plugin is not usable.

**Comment by triniwiz** [comment]
It should be possible if you use [this](https://github.com/triniwiz/nativescript-nested-scrollview)
