### ISSUE TITLE
not working in Nativescript 2.5 

### ISSUE THREAD

**Issue by c1ngular** [triniwiz/nativescript-accordion#5]
hi , i have tried to run the demo from this repository , but failed on both iOS and Android platforms !
**on iOS(simulator) just crashed , from terminal i can see message as below :** 

`
Command xcrun with arguments simctl launch B4938CAB-C64B-4BF3-B4DA-7F31F2607E39 org.nativescript.demo failed with exit code 1. Error output:
 An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
The request to open "org.nativescript.demo" failed.
The request was denied by service delegate (SBMainWorkspace) for reason: NotFound ("Application "org.nativescript.demo" is unknown to FrontBoard").

`

**on Android (device):**

`
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.demo/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreate failed

Error: Building UI from XML. @file:///app/main-page.xml:4:9
 > Module '/data/data/org.nativescript.demo/files/app/nativescript-accordion' not found for element 'nativescript-accordion:Accordion'.
   > com.tns.NativeScriptException: Failed to find module: "/data/data/org.nativescript.demo/files/app/nativescript-accordion", relative to: app//
      com.tns.Module.resolvePathHelper(Module.java:159)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
    com.tns.Runtime.callJSMethod(Runtime.java:1047)
    com.tns.Runtime.callJSMethod(Runtime.java:1028)
    com.tns.Runtime.callJSMethod(Runtime.java:1018)
    com.tns.NativeScriptActivity.onCreate(android.app.Activity.java)
    android.app.Activity.performCreate(Activity.java:6367)
    android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
    android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2397)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2504)
    android.app.ActivityThread.access$900(ActivityThread.java:165)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:150)
    android.app.ActivityThread.main(ActivityThread.java:5546)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
File: "file:///data/data/org.nativescript.demo/files/app/tns_modules/tns-core-modules/ui/builder/builder.js, line: 175, column: 20

StackTrace: 
 Frame: function:'', file:'file:///data/data/org.nativescript.demo/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 175, column: 21
 Frame: function:'', file:'file:///data/data/org.nativescript.demo/files/app/tns_modules/tns-core-modules/xml/xml.js', line: 148, column: 13
 Frame: function:'EasySAXParser.parse', file:'file:///data/data/org.nativescript.demo/files/app/tns_modules/tns-core-modules/js-libs/easysax/easysax.js', line: 751, column: 23
 Frame: function:'XmlParser.parse', file:'file:///data/data/org.nativescript.demo/files/app/tns_modules/tns-core-modules/xml/xml.js', line: 195, column: 22
 Frame: function:'XmlStringParser.parse', file:'file:///data/data/org.nativescript.demo/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 181, column: 27
 Frame: function:'parseInternal', file:'file:///data/data/org.nativescript.demo/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 48, column: 11
 Frame: function:'loadInternal', file:'file:///data/data/org.nativescript.demo/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 133, column: 27
 Frame: function:'load', file:'file:///data/data/org.nativescript.demo/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 117, column: 27
 Frame: function:'pageFromBuilder', file:'file:///data/data/org.nativescript.demo/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 111, column: 27
 Frame: function:'resolvePageFromEntry', file:'file:///data/data/org.nativescript.demo/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 89, column: 20
 Frame: function:'Frame.navigate', file:'file:///data/data/org.nativescript.demo/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 165, column: 20
 Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.demo/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 690, column: 19
 Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.demo/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 13, column: 25

 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2444)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2504)
 at android.app.ActivityThread.access$900(ActivityThread.java:165)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:150)
 at android.app.ActivityThread.main(ActivityThread.java:5546)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
Caused by: com.tns.NativeScriptException: 
Calling js method onCreate failed

Error: Building UI from XML. @file:///app/main-page.xml:4:9
 > Module '/data/data/org.nativescript.demo/files/app/nativescript-accordion' not found for element 'nativescript-accordion:Accordion'.
   > com.tns.NativeScriptException: Failed to find module: "/data/data/org.nativescript.demo/files/app/nativescript-accordion", relative to: app//
      com.tns.Module.resolvePathHelper(Module.java:159)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
    com.tns.Runtime.callJSMethod(Runtime.java:1047)
    com.tns.Runtime.callJSMethod(Runtime.java:1028)
    com.tns.Runtime.callJSMethod(Runtime.java:1018)
    com.tns.NativeScriptActivity.onCreate(android.app.Activity.java)
    android.app.Activity.performCreate(Activity.java:6367)
    android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
    android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2397)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2504)
    android.app.ActivityThread.access$900(ActivityThread.java:165)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:150)
    android.app.ActivityThread.main(ActivityThread.java:5546)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
File: "file:///data/data/org.nativescript.demo/files/app/tns_modules/tns-core-modules/ui/builder/builder.js, line: 175, column: 20

StackTrace: 
 Frame: function:'', file:'file:///data/data/org.nativescript.demo/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 175, column: 21
 Frame: function:'', file:'file:///data/data/org.nativescript.demo/files/app/tns_modules/tns-core-modules/xml/xml.js', line: 148, column: 13
 Frame: function:'EasySAXParser.parse', file:'file:///data/data/org.nativescript.demo/files/app/tns_modules/tns-core-modules/js-libs/easysax/easysax.js', line: 751, column: 23
 Frame: function:'XmlParser.parse', file:'file:///data/data/org.nativescript.demo/files/app/tns_modules/tns-core-modules/xml/xml.js', line: 195, column: 22
 Frame: function:'XmlStringParser.parse', file:'file:///data/data/org.nativescript.demo/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 181, column: 27
 Frame: function:'parseInternal', file:'file:///data/data/org.nativescript.demo/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 48, column: 11
 Frame: function:'loadInternal', file:'file:///data/data/org.nativescript.demo/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 133, column: 27
 Frame: function:'load', file:'file:///data/data/org.nativescript.demo/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 117, column: 27
 Frame: function:'pageFromBuilder', file:'file:///data/data/org.nativescript.demo/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 111, column: 27
 Frame: function:'resolvePageFromEntry', file:'file:///data/data/org.nativescript.demo/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 89, column: 20
 Frame: function:'Frame.navigate', file:'file:///data/data/org.nativescript.demo/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 165, column: 20
 Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.demo/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 690, column: 19
 Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.demo/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 13, column: 25

 at com.tns.Runtime.callJSMethodNative(Native Method)
 at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
 at com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
 at com.tns.Runtime.callJSMethod(Runtime.java:1047)
 at com.tns.Runtime.callJSMethod(Runtime.java:1028)
 at com.tns.Runtime.callJSMethod(Runtime.java:1018)
 at com.tns.NativeScriptActivity.onCreate(android.app.Activity.java)
 at android.app.Activity.performCreate(Activity.java:6367)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2397)
 ... 9 more

`

thanks

**Comment by bradmartin** [comment]
That error indicates one of two things. If using angular you didn't call `registerElement()` if plain NS, you didn't add the xmlns on the Page. see here https://github.com/triniwiz/nativescript-accordion#usage
