### ISSUE TITLE
How to remove padding between items?

### ISSUE THREAD

**Issue by meysam-mahmoodi** [triniwiz/nativescript-accordion#52]
Hello

this is my code:
```
            <Accordion class="accordion" [items]="items" itemTapped="tapped" headerTextBold="true" headerTextColor="white" headerColor="pink"
                headerTextColor="blue" allowMultiple="false" selectedIndex="2">
            
                <ng-template accordionHeaderTemplate let-item="item" let-i="index">
                    <GridLayout class="header" columns="auto,*">
                        <Label [text]="item.title" textWrap="true"></Label>
                    </GridLayout>
                </ng-template>
            
                <ng-template accordionItemTemplate let-item="item" let-parent="parentIndex" let-even="even" let-child="childIndex">
                    <StackLayout class="body">
                        <Label [text]="item.text" textWrap="true"></Label>
                    </StackLayout>
                </ng-template>
            
            </Accordion>
```
this is my css:
```
.accordion{
  border-width: 1px;
  border-color: #f3f3f3;
}

.header{
  box-shadow: 4;
  background-color: #fff;
  padding: 10 15;
}
.body{
  padding: 10 15;
  background-color: #fff;
}
```
and this is output of that:
![image](https://user-images.githubusercontent.com/39044062/48301973-459b3280-e50b-11e8-9732-94d54e990e42.png)

how can i remove gray padding or change height of that?
thanks

**Comment by triniwiz** [comment]
Which version are you using ? I'm guessing it's an older version because of the markup

**Comment by meysam-mahmoodi** [comment]
this is at my package.json:
`"nativescript-accordion": "^5.0.4",`

**Comment by triniwiz** [comment]
Try installing the new beta version 


Sent from Yahoo Mail for iPhone


On Sunday, November 11, 2018, 1:43 AM, Meysam Mahmoudi <notifications@github.com> wrote:


this is at my package.json:
"nativescript-accordion": "^5.0.4",

**Comment by meysam-mahmoodi** [comment]
I updated my plugin to `6.0.0-beta.1 version` and padding was removed but when I tap on title of every title, it doesn't work (doesn't open to show content)  and after tapping that, app will be closed automatically
![image](https://user-images.githubusercontent.com/39044062/48336037-a2662c80-e674-11e8-8af3-42b9d9979bdc.png)

**Comment by triniwiz** [comment]
Did you update your code to follow the new template requirements?

**Comment by meysam-mahmoodi** [comment]
after updating new template, the problem was solved. thank you
