### ISSUE TITLE
Output [object Object] on angular

### ISSUE THREAD

**Issue by moorateeahtashil** [triniwiz/nativescript-accordion#60]
On interface when i display the data it shows object object rather than the data

**Comment by triniwiz** [comment]
Did u import the module ?

**Comment by moorateeahtashil** [comment]
Yes I did import all the necessary module

#CODE BELOW

export class MenuComponent implements OnInit {

	public cafe:string;
    public tabSelectedIndex: number;
    

    public menus: any;
    public selectedIndexes = [0, 1];
    public sum:number;

	 @ViewChild('actionbartitle') actionbartitle : ElementRef;


    public constructor(private route: ActivatedRoute) {
        this.sum=0;
        this.tabSelectedIndex = 0;
        
       
    }

    ngOnInit(): any {

    	const myTitle: Label = <Label>this.actionbartitle.nativeElement;


        this.route.queryParams.subscribe(params => {
            this.cafe = params["Cafe_Name"];
  			
        });

    	myTitle.text=this.cafe;
        

        this.menus = [
            {
                title: "10",
                footer: "10",
                headerText: "First",
                footerText: "4",
                image: 'http://placehold.it/120x120&text=First',
                items: "bol"
            }];
    }
}


menu.component.html


<StackLayout class="p-20">
  <Accordion height="100%" [items]="menus" [selectedIndexes]="selectedIndexes">
    <ng-template let-i="index" let-menu="item" acTemplateKey="header">
      <StackLayout>
        <Label  [text]="menu.headerText"></Label>
      </StackLayout>
    </ng-template>


    <ng-template let-i="index" let-menu="item" acTemplateKey="title">
      <GridLayout>
        <Label height="100%" [text]="menu.title"></Label>
      </GridLayout>
    </ng-template>

    <ng-template let-i="index" let-menu="item" acTemplateKey="content">
      <StackLayout>
        <Label [text]="menu.text"></Label>
      </StackLayout>
    </ng-template>


    <ng-template let-i="index" let-menu="item" acTemplateKey="footer">
      <StackLayout>
        <Label [text]="menu.footerText"></Label>
      </StackLayout>
    </ng-template>
  </Accordion>
</StackLayout>




when i set items to "bol" it create a accordion with the open menu with each character as a index

![screenshot_20190219-230134](https://user-images.githubusercontent.com/30066932/53040293-0f951500-344f-11e9-9cc5-b336271e49bb.png)

**Comment by triniwiz** [comment]
I’m am still seeing where u imported the accordion module

**Comment by moorateeahtashil** [comment]
on app.module.ts

import { NgModule, NO_ERRORS_SCHEMA } from "@angular/core";
import { NativeScriptModule } from "nativescript-angular/nativescript.module";
import { NativeScriptUISideDrawerModule } from "nativescript-ui-sidedrawer/angular";
import { NativeScriptFormsModule } from "nativescript-angular/forms";
import { AppRoutingModule } from "./app-routing.module";
import { AppComponent } from "./app.component";
import {DatePipe} from '@angular/common';
import { TNSCheckBoxModule } from 'nativescript-checkbox/angular';
import { AccordionModule } from "nativescript-accordion/angular";

@NgModule({
    bootstrap: [
        AppComponent
    ],
    imports: [
        AppRoutingModule,
        NativeScriptModule,
        NativeScriptUISideDrawerModule,
        NativeScriptFormsModule,
        AccordionModule,
        TNSCheckBoxModule
    ],
    declarations: [
        AppComponent
    ],
    schemas: [
        NO_ERRORS_SCHEMA
    ],
    providers: [
        DatePipe
    ],
})
export class AppModule { }

**Comment by triniwiz** [comment]
So the by default the plugin looks for a structure like [this](https://github.com/triniwiz/nativescript-accordion/blob/master/demo-ng/src/app/main/main.component.ts#L22-L32)

```ts
 [{
                title: '1',
                footer: '10',
                headerText: 'First',
                footerText: '4',
                image: 'http://placehold.it/120x120&text=First',
                items: [{image: '~/images/a9ff17db85f8136619feb0d5a200c0e4.png', text: 'Stop'}, {
                    text: 'Drop',
                    image: '~/images/shazam.jpg'
                }]
            }...]
```

But you can set the child items prop 

```html
<Accordion childItems="children" [items]="items">
```

```ts
[
{
                title: '1',
                footer: '10',
                headerText: 'First',
                footerText: '4',
                image: 'http://placehold.it/120x120&text=First',
                children: [
                    {image: '~/images/a9ff17db85f8136619feb0d5a200c0e4.png', text: 'Someone'},
                    {
                        text: 'Help',
                        image: '~/images/svg.jpg'
                    }
                ]
            }
...]
```

**Comment by moorateeahtashil** [comment]
When using the default plugin i am getting an [object Object] accordion, even if i remove all the <ng template> tags with just the accordion tag , i would get the same result.

When using the childItems , i am getting the error :
TypeError : Cannot read property 'length' of undefined.

**Comment by triniwiz** [comment]
Can u share your data structure?

**Comment by moorateeahtashil** [comment]
I will just post the whole code for this page

menu.component.html
```html
<ActionBar class="action-bar">
	<StackLayout orientation="horizontal">
    <Label #actionbartitle class="action-bar-title" textwrap="true"></Label>
    </StackLayout>
</ActionBar>


<GridLayout class="page page-content">
<!-- 	<TabView>
	    <StackLayout *tabItem="{title: 'Courses'}" > -->
	    
<StackLayout class="p-20">
 
  <Accordion height="100%" [items]="items" allowMultiple="false" [selectedIndexes]="selectedIndexes">

    <ng-template let-i="index" let-item="item" acTemplateKey="header">
      <StackLayout>
        <Label  [text]="item.headerText"></Label>
      </StackLayout>
    </ng-template>


    <ng-template let-i="index" let-item="item" acTemplateKey="title">
      <GridLayout>
        <Label height="100%" [text]="item.title"></Label>
      </GridLayout>
    </ng-template>

    <ng-template let-i="index" let-item="item" acTemplateKey="content">
      <StackLayout>
        <Label [text]="item.text"></Label>
      </StackLayout>
    </ng-template>


    <ng-template let-i="index" let-item="item" acTemplateKey="footer">
      <StackLayout>
        <Label [text]="item.footerText"></Label>
      </StackLayout>
    </ng-template>
  </Accordion>
</StackLayout>



	  <!--   <StackLayout *tabItem="{title: 'Drinks'}">
	    	<ListView [items]="cafes2" class="list-group">
   		 		<ng-template let-cafe2="item" let-i="index" let-odd="odd" let-even="even" let-myIndex="index">
       				<StackLayout orientation="vertical" class="list-group-item">
           				 <Label [text]="cafe2.name"></Label>
           				 <Label [text]="cafe2.description"></Label>
           				 <Label [text]="cafe2.price"></Label>
           				 <Button id="{{ 'btn_' + $index }}" text="Add to cart" (tap)="adddrinktocart($event,myIndex)"></Button>
        			</StackLayout>
   				 </ng-template>
			</ListView>
	    </StackLayout>

	     <StackLayout *tabItem="{title: 'Cart'}">
	    	
           		<Button text="Calculate" (tap)="calculateprice()"></Button>
        			
	    </StackLayout>
    </TabView> -->

    

</GridLayout>

```
and the menu.component.ts

```ts
import { Component, OnInit } from "@angular/core";
import { RadSideDrawer } from "nativescript-ui-sidedrawer";
import * as app from "tns-core-modules/application";
import {ActivatedRoute} from "@angular/router";
import { ObservableArray, ChangedData } from "tns-core-modules/data/observable-array"
import {ElementRef, ViewChild} from "@angular/core";
import { StackLayout } from 'ui/layouts/stack-layout';
import { Label } from 'ui/label';
import { menuItem } from './menuItem';
import {EventData} from "data/observable"



@Component({
    selector: "Menu",
    moduleId: module.id,
    templateUrl: "./menu.component.html"
})


export class MenuComponent implements OnInit {

	public cafe:string;
    public tabSelectedIndex: number;
    

    public items: any[];
    public selectedIndexes = [0, 1];
    public sum:number;

	 @ViewChild('actionbartitle') actionbartitle : ElementRef;


    public constructor(private route: ActivatedRoute) {
        this.sum=0;
        this.tabSelectedIndex = 0;
        
       
    }

    ngOnInit(): any {

    	const myTitle: Label = <Label>this.actionbartitle.nativeElement;


        this.route.queryParams.subscribe(params => {
            this.cafe = params["Cafe_Name"];
  			
        });

    	myTitle.text=this.cafe;
        

        this.items = [
            {
                title: '10',
                footer: '10',
                headerText: 'First',
                footerText: '4',
                image: 'http://placehold.it/120x120&text=First',
                items: [{image: '~/images/a9ff17db85f8136619feb0d5a200c0e4.png', text: 'Stop'}, {
                    text: 'Drop',
                    image: '~/images/shazam.jpg'
                }]
            }];

            console.log(this.items);
    }

    

}
```

If you find any error do tell me , thank you

**Comment by triniwiz** [comment]
`public selectedIndexes = [0, 1];` you have two selectedIndexes but your items size is 1

**Comment by moorateeahtashil** [comment]
The page does load with the following output

When the page is loaded
![screenshot_20190219-234021](https://user-images.githubusercontent.com/30066932/53042484-618c6980-3454-11e9-85e7-6f0cf2710d7e.png)

when i close the accordion
![screenshot_20190219-234025](https://user-images.githubusercontent.com/30066932/53042475-5cc7b580-3454-11e9-9718-f2fcbd178886.png)

**Comment by triniwiz** [comment]
Are you using multiple modules by chance ?

**Comment by moorateeahtashil** [comment]
These arre all the module i am using in this project

from app.module.ts

import { NgModule, NO_ERRORS_SCHEMA } from "@angular/core";
import { NativeScriptModule } from "nativescript-angular/nativescript.module";
import { NativeScriptUISideDrawerModule } from "nativescript-ui-sidedrawer/angular";
import { NativeScriptFormsModule } from "nativescript-angular/forms";
import { AppRoutingModule } from "./app-routing.module";
import { AppComponent } from "./app.component";
import {DatePipe} from '@angular/common';
import { TNSCheckBoxModule } from 'nativescript-checkbox/angular';
import { AccordionModule } from "nativescript-accordion/angular";

@NgModule({
    bootstrap: [
        AppComponent
    ],
    imports: [
        AppRoutingModule,
        NativeScriptModule,
        NativeScriptUISideDrawerModule,
        NativeScriptFormsModule,
        AccordionModule,
        TNSCheckBoxModule
    ],
    declarations: [
        AppComponent
    ],
    schemas: [
        NO_ERRORS_SCHEMA
    ],
    providers: [
        DatePipe
    ],
})
export class AppModule { }


from menu.module.ts

import { NgModule, NO_ERRORS_SCHEMA } from "@angular/core";
import { NativeScriptCommonModule } from "nativescript-angular/common";
import { MenuRoutingModule } from "./menu-routing.module";
import { MenuComponent } from "./menu.component";

@NgModule({
    imports: [
        NativeScriptCommonModule,
        MenuRoutingModule,

    ],
    declarations: [
        MenuComponent
    ],
    schemas: [
        NO_ERRORS_SCHEMA
    ]
})
export class MenuModule { }

**Comment by triniwiz** [comment]
There is your problem you did not import it into the menu module :)

**Comment by moorateeahtashil** [comment]
Thanks a lot it worked
