### ISSUE TITLE
Angular ngFor Support

### ISSUE THREAD

**Issue by smarza** [triniwiz/nativescript-accordion#7]
Hi,

@triniwiz, does nativescript-accordion supports *ngFor to repete items?

I just tried to do so, but it didn't work in my project.

Thanks in advance.

**Comment by triniwiz** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } On iOS it works for sure android needs an update


Sent from Yahoo Mail for iPhone


On Sunday, February 19, 2017, 8:45 AM, smarza <notifications@github.com> wrote:


Hi,

@triniwiz, does nativescript-accordion supports *ngFor to repete items?

I just tried to do so, but it didn't work in my project.

Thanks in advance.

**Comment by smarza** [comment]
@triniwiz 
That's exactly the case. lol
Android is the target platform for this project.

Do you have any scheduling for the android update?

Please, let me know when you have time to see the issue about custom headers.
[](https://github.com/triniwiz/nativescript-accordion/issues/6)

Thank you very much for the quick response.

**Comment by triniwiz** [comment]
Please update
