### ISSUE TITLE
headerTextAligment don't align properly.

### ISSUE THREAD

**Issue by GlisboaDev** [triniwiz/nativescript-accordion#8]
I'm playing a bit with the library and I noticed while `left` works fine, `center` and `right` alignment doesn't apply correctly. Is it a bug or am I missing any setting?
Center:
<img width="379" alt="center alignment" src="https://cloud.githubusercontent.com/assets/8302455/23183206/4100de1a-f849-11e6-8e53-3bc1212b7564.png">
Right:
<img width="380" alt="right alignment" src="https://cloud.githubusercontent.com/assets/8302455/23183209/4374604a-f849-11e6-996c-8ec28fdc6bd4.png">

**Comment by triniwiz** [comment]
Fixed in 3.0
